### PR TITLE
test: simplify PostgreSQL test and app

### PR DESCRIPTION
**Pull request by blgm**
There's some confusion in the test and app as to whether schemas are
being tested. The test thinks that they are, but the app doesn't
actually put data in the schema. This update simplifies the test and app to no
longer attempt to test schemas. The simplest way to use the PostgreSQL
service is just to use the pre-existing "public" schema.

[#181059797](https://www.pivotaltracker.com/story/show/181059797)

### Checklist:

* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
* [X] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

### CODE REVIEW

**Comment by FelisiaM** [comment]
I agree that the simplest way to test Postgres is to use public schema and the app was not set up correctly to use the schema one created.

However, the schema creation and dropping assertions were added intentionally as part of the story to test user permissions. I would suggest we keep the schema and  fix the set and get handlers to read the schema and act on it rather then removing it all together.

**Review by FelisiaM — COMMENTED** [review]
I agree that the public schema is the easiest thing to do and that the app was not properly using it to set and get.

However, the schema creation and dropping were added intentionally as part of the user permission story. I would be keener to have the `get` and `set` handlers make use of the schema rather than `public.table-name` then have the schema removed completely

**Comment by blgm** [comment]
Is there something special about schemas that makes it worthwhile to test them over and above other resources?

**Comment by blgm** [comment]
We had a conversation in person. The summary is that testing the deletion of a schema is useful as it triggers the change in ownership. Maybe there are other objects that we could test, but given we already have the schema code, it makes sense to use that. Let's close this PR for now, and I'll submit a new one if needed.

**Pull request closed without merging**
